This notebook was composed through the training received from the Guided Project "Death Medical Analysis & Visualization using Plotly" on Coursera.  The course, however, uses Google Colab, and goes much more in-depth.  This notebook covers only selected topics and some additional information built over time.  Highly recommend you visit the [Course](https://www.coursera.org/projects/covid-19-death-medical-analysis-visualization-using-plotly) and see for yourself what it can offer.

### Importing Libraries

In [1]:
#Data analysis and Manipulation
import pandas as pd       

#Data Visualization
import plotly.express as px    
import matplotlib.pyplot as plt

In [2]:
import plotly.io as pio

### Importing Datasets

In [3]:
df2 = pd.read_csv('US_medical_data.csv')

In [4]:
df2

,Data as of,Start Week,End Week,State,Condition Group,Condition,ICD10_codes,Age Group,COVID-19 Deaths,Number of Mentions,Flag
0,1/10/2021,1/4/2020,1/9/2021,US,Respiratory diseases,Influenza and pneumonia,J09-J18,0-24,198.0,205.0,NaN
1,1/10/2021,1/4/2020,1/9/2021,US,Respiratory diseases,Influenza and pneumonia,J09-J18,25-34,968.0,985.0,NaN
2,1/10/2021,1/4/2020,1/9/2021,US,Respiratory diseases,Influenza and pneumonia,J09-J18,35-44,2537.0,2584.0,NaN
3,1/10/2021,1/4/2020,1/9/2021,US,Respiratory diseases,Influenza and pneumonia,J09-J18,45-54,7369.0,7555.0,NaN
4,1/10/2021,1/4/2020,1/9/2021,US,Respiratory diseases,Influenza and pneumonia,J09-J18,55-64,18378.0,18829.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
12415,1/10/2021,1/4/2020,1/9/2021,PR,COVID-19,COVID-19,U071,65-74,321.0,321.0,NaN
12416,1/10/2021,1/4/2020,1/9/2021,PR,COVID-19,COVID-19,U071,75-84,366.0,366.0,NaN
12417,1/10/2021,1/4/2020,1/9/2021,PR,COVID-19,COVID-19,U071,85+,264.0,264.0,NaN
12418,1/10/2021,1/4/2020,1/9/2021,PR,COVID-19,COVID-19,U071,Not stated,0.0,0.0,NaN
12419,1/10/2021,1/4/2020,1/9/2021,PR,COVID-19,COVID-19,U071,All Ages,1290.0,1290.0,NaN

### Analysis

Seeing the distribution by a couple of variables:
- Grouping by by State
- Grouping by Condition Group
- Grouping by Age Group

#### Grouping by various columns

In [5]:
df2.groupby(['State']).count()

,Data as of,Start Week,End Week,Condition Group,Condition,ICD10_codes,Age Group,COVID-19 Deaths,Number of Mentions,Flag
State,,,,,,,,,,
AK,230,230,230,230,230,230,230,128,128,102
AL,230,230,230,230,230,230,230,186,189,44
AR,230,230,230,230,230,230,230,185,186,45
AZ,230,230,230,230,230,230,230,195,197,35
CA,230,230,230,230,230,230,230,209,210,21
CO,230,230,230,230,230,230,230,178,181,52
CT,230,230,230,230,230,230,230,181,183,49
DC,230,230,230,230,230,230,230,164,165,66
DE,230,230,230,230,230,230,230,140,142,90
FL,230,230,230,230,230,230,230,200,201,30
GA,230,230,230,230,230,230,230,196,196,34
HI,230,230,230,230,230,230,230,135,137,95
IA,230,230,230,230,230,230,230,182,184,48
ID,230,230,230,230,230,230,230,170,172,60
IL,230,230,230,230,230,230,230,195,198,35
IN,230,230,230,230,230,230,230,190,191,40
KS,230,230,230,230,230,230,230,171,174,59
KY,230,230,230,230,230,230,230,187,187,43
LA,230,230,230,230,230,230,230,185,187,45
MA,230,230,230,230,230,230,230,177,179,53
MD,230,230,230,230,230,230,230,179,182,51
ME,230,230,230,230,230,230,230,158,161,72
MI,230,230,230,230,230,230,230,191,191,39
MN,230,230,230,230,230,230,230,184,185,46
MO,230,230,230,230,230,230,230,180,180,50
MS,230,230,230,230,230,230,230,190,191,40
MT,230,230,230,230,230,230,230,169,174,61
NC,230,230,230,230,230,230,230,185,186,45
ND,230,230,230,230,230,230,230,167,170,63
NE,230,230,230,230,230,230,230,178,180,52
NH,230,230,230,230,230,230,230,170,172,60
NJ,230,230,230,230,230,230,230,193,196,37
NM,230,230,230,230,230,230,230,175,175,55
NV,230,230,230,230,230,230,230,182,186,48
NY,230,230,230,230,230,230,230,180,185,50
OH,230,230,230,230,230,230,230,186,188,44
OK,230,230,230,230,230,230,230,185,188,45
OR,230,230,230,230,230,230,230,176,180,54
PA,230,230,230,230,230,230,230,188,190,42
PR,230,230,230,230,230,230,230,170,171,60
RI,230,230,230,230,230,230,230,170,172,60
SC,230,230,230,230,230,230,230,188,190,42
SD,230,230,230,230,230,230,230,173,177,57
TN,230,230,230,230,230,230,230,180,181,50
TX,230,230,230,230,230,230,230,210,211,20
US,230,230,230,230,230,230,230,230,230,0
UT,230,230,230,230,230,230,230,164,166,66
VA,230,230,230,230,230,230,230,178,179,52
VT,230,230,230,230,230,230,230,147,148,83
WA,230,230,230,230,230,230,230,175,177,55
WI,230,230,230,230,230,230,230,184,185,46
WV,230,230,230,230,230,230,230,167,169,63
WY,230,230,230,230,230,230,230,147,151,83
YC,230,230,230,230,230,230,230,197,199,33

In [6]:
df2.groupby(['State']).count()

,Data as of,Start Week,End Week,Condition Group,Condition,ICD10_codes,Age Group,COVID-19 Deaths,Number of Mentions,Flag
State,,,,,,,,,,
AK,230,230,230,230,230,230,230,128,128,102
AL,230,230,230,230,230,230,230,186,189,44
AR,230,230,230,230,230,230,230,185,186,45
AZ,230,230,230,230,230,230,230,195,197,35
CA,230,230,230,230,230,230,230,209,210,21
CO,230,230,230,230,230,230,230,178,181,52
CT,230,230,230,230,230,230,230,181,183,49
DC,230,230,230,230,230,230,230,164,165,66
DE,230,230,230,230,230,230,230,140,142,90
FL,230,230,230,230,230,230,230,200,201,30
GA,230,230,230,230,230,230,230,196,196,34
HI,230,230,230,230,230,230,230,135,137,95
IA,230,230,230,230,230,230,230,182,184,48
ID,230,230,230,230,230,230,230,170,172,60
IL,230,230,230,230,230,230,230,195,198,35
IN,230,230,230,230,230,230,230,190,191,40
KS,230,230,230,230,230,230,230,171,174,59
KY,230,230,230,230,230,230,230,187,187,43
LA,230,230,230,230,230,230,230,185,187,45
MA,230,230,230,230,230,230,230,177,179,53
MD,230,230,230,230,230,230,230,179,182,51
ME,230,230,230,230,230,230,230,158,161,72
MI,230,230,230,230,230,230,230,191,191,39
MN,230,230,230,230,230,230,230,184,185,46
MO,230,230,230,230,230,230,230,180,180,50
MS,230,230,230,230,230,230,230,190,191,40
MT,230,230,230,230,230,230,230,169,174,61
NC,230,230,230,230,230,230,230,185,186,45
ND,230,230,230,230,230,230,230,167,170,63
NE,230,230,230,230,230,230,230,178,180,52
NH,230,230,230,230,230,230,230,170,172,60
NJ,230,230,230,230,230,230,230,193,196,37
NM,230,230,230,230,230,230,230,175,175,55
NV,230,230,230,230,230,230,230,182,186,48
NY,230,230,230,230,230,230,230,180,185,50
OH,230,230,230,230,230,230,230,186,188,44
OK,230,230,230,230,230,230,230,185,188,45
OR,230,230,230,230,230,230,230,176,180,54
PA,230,230,230,230,230,230,230,188,190,42
PR,230,230,230,230,230,230,230,170,171,60
RI,230,230,230,230,230,230,230,170,172,60
SC,230,230,230,230,230,230,230,188,190,42
SD,230,230,230,230,230,230,230,173,177,57
TN,230,230,230,230,230,230,230,180,181,50
TX,230,230,230,230,230,230,230,210,211,20
US,230,230,230,230,230,230,230,230,230,0
UT,230,230,230,230,230,230,230,164,166,66
VA,230,230,230,230,230,230,230,178,179,52
VT,230,230,230,230,230,230,230,147,148,83
WA,230,230,230,230,230,230,230,175,177,55
WI,230,230,230,230,230,230,230,184,185,46
WV,230,230,230,230,230,230,230,167,169,63
WY,230,230,230,230,230,230,230,147,151,83
YC,230,230,230,230,230,230,230,197,199,33

In [7]:
df2.groupby(['Condition Group']).count()

,Data as of,Start Week,End Week,State,Condition,ICD10_codes,Age Group,COVID-19 Deaths,Number of Mentions,Flag
Condition Group,,,,,,,,,,
All other conditions and causes (residual),540,540,540,540,540,540,540,460,485,80
Alzheimer disease,540,540,540,540,540,540,540,459,459,81
COVID-19,540,540,540,540,540,540,540,481,481,59
Circulatory diseases,3780,3780,3780,3780,3780,3780,3780,2889,2897,891
Diabetes,540,540,540,540,540,540,540,437,437,103
"Intentional and unintentional injury, poisoning, and other adverse events",540,540,540,540,540,540,540,353,412,187
Malignant neoplasms,540,540,540,540,540,540,540,394,398,146
Obesity,540,540,540,540,540,540,540,372,372,168
Renal failure,540,540,540,540,540,540,540,420,422,120
Respiratory diseases,3240,3240,3240,3240,3240,3240,3240,2501,2506,739
Sepsis,540,540,540,540,540,540,540,411,411,129
Vascular and unspecified dementia,540,540,540,540,540,540,540,473,473,67

In [8]:
df2.groupby(['Age Group']).count()

,Data as of,Start Week,End Week,State,Condition Group,Condition,ICD10_codes,COVID-19 Deaths,Number of Mentions,Flag
Age Group,,,,,,,,,,
0-24,1242,1242,1242,1242,1242,1242,1242,804,812,438
25-34,1242,1242,1242,1242,1242,1242,1242,654,670,588
35-44,1242,1242,1242,1242,1242,1242,1242,679,700,563
45-54,1242,1242,1242,1242,1242,1242,1242,816,837,426
55-64,1242,1242,1242,1242,1242,1242,1242,960,971,282
65-74,1242,1242,1242,1242,1242,1242,1242,1081,1092,161
75-84,1242,1242,1242,1242,1242,1242,1242,1126,1131,116
85+,1242,1242,1242,1242,1242,1242,1242,1101,1108,141
All Ages,1242,1242,1242,1242,1242,1242,1242,1203,1206,39
Not stated,1242,1242,1242,1242,1242,1242,1242,1226,1226,16